<#include 'macros/main.ftlh'>

<@page>
    <h2>User</h2>
    <div>
        <input type="button" class="btn btn-info" value="User routes" onclick="location.href='userRoutes'">
        <input type="button" class="btn btn-info" value="Driver schedule" onclick="location.href='driverSchedule'">
        <input type="button" class="btn btn-info" value="Driver route" onclick="location.href='driverRoute'">
    </div>
</@page>

